// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          int64            `json:"id"`
	CustomerRef string           `json:"customer_ref"`
	TotalPrice  int32            `json:"total_price"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	IsDeleted   bool             `json:"is_deleted"`
}

type OrderItem struct {
	ID        int64            `json:"id"`
	OrderID   int64            `json:"order_id"`
	ProductID int64            `json:"product_id"`
	Quantity  int32            `json:"quantity"`
	UnitPrice int32            `json:"unit_price"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	IsDeleted bool             `json:"is_deleted"`
}

type Product struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Price       int32            `json:"price"`
	Stock       int32            `json:"stock"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
