// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package repo

import (
	"context"
)

const addOrderItem = `-- name: AddOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, unit_price)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, unit_price, created_at, is_deleted
`

type AddOrderItemParams struct {
	OrderID   int64 `json:"order_id"`
	ProductID int64 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
	UnitPrice int32 `json:"unit_price"`
}

func (q *Queries) AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, addOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_ref)
VALUES ($1)
RETURNING id, customer_ref, total_price, created_at, is_deleted
`

func (q *Queries) CreateOrder(ctx context.Context, customerRef string) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, customerRef)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerRef,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
UPDATE orders
SET is_deleted = true
WHERE id = $1 AND is_deleted = false
`

func (q *Queries) DeleteOrder(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const deleteOrderItemsByOrderID = `-- name: DeleteOrderItemsByOrderID :exec
UPDATE order_items
SET is_deleted = true
WHERE order_id = $1 AND is_deleted = false
`

func (q *Queries) DeleteOrderItemsByOrderID(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, deleteOrderItemsByOrderID, orderID)
	return err
}

const getAllOrders = `-- name: GetAllOrders :many
SELECT id, customer_ref, total_price, created_at, is_deleted FROM orders
WHERE is_deleted = false
ORDER BY created_at DESC
`

func (q *Queries) GetAllOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, getAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerRef,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrder = `-- name: GetOrder :one
SELECT id, customer_ref, total_price, created_at, is_deleted FROM orders
WHERE id = $1 and is_deleted = false
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerRef,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getOrdersByCustomerRef = `-- name: GetOrdersByCustomerRef :many
SELECT id, customer_ref, total_price, created_at, is_deleted FROM orders
WHERE customer_ref = $1 and is_deleted = false
ORDER BY created_at DESC
`

func (q *Queries) GetOrdersByCustomerRef(ctx context.Context, customerRef string) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByCustomerRef, customerRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerRef,
			&i.TotalPrice,
			&i.CreatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, quantity, unit_price, created_at, is_deleted FROM order_items
WHERE order_id = $1 and is_deleted = false
ORDER BY created_at DESC
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID int64) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.CreatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderTotalPrice = `-- name: UpdateOrderTotalPrice :one
UPDATE orders
SET total_price = $1, created_at = NOW()
WHERE id = $2 and is_deleted = false
RETURNING id, customer_ref, total_price, created_at, is_deleted
`

type UpdateOrderTotalPriceParams struct {
	TotalPrice int32 `json:"total_price"`
	ID         int64 `json:"id"`
}

func (q *Queries) UpdateOrderTotalPrice(ctx context.Context, arg UpdateOrderTotalPriceParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderTotalPrice, arg.TotalPrice, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerRef,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}
