// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error)
	CreateOrder(ctx context.Context, customerRef string) (Order, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteOrder(ctx context.Context, id int64) error
	DeleteOrderItemsByOrderID(ctx context.Context, orderID int64) error
	DeleteProduct(ctx context.Context, id int64) error
	FindProductByID(ctx context.Context, id int64) (Product, error)
	GetAllOrders(ctx context.Context) ([]Order, error)
	GetOrder(ctx context.Context, id int64) (Order, error)
	GetOrdersByCustomerRef(ctx context.Context, customerRef string) ([]Order, error)
	GetProductByName(ctx context.Context, name string) (Product, error)
	GetProductsByIDs(ctx context.Context, id int64) ([]Product, error)
	ListOrderItems(ctx context.Context, orderID int64) ([]OrderItem, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ProductExists(ctx context.Context, name string) (bool, error)
	SearchProductsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Product, error)
	UpdateOrderTotalPrice(ctx context.Context, arg UpdateOrderTotalPriceParams) (Order, error)
	UpdateProductDetails(ctx context.Context, arg UpdateProductDetailsParams) (Product, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
